/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scy_voicechanger_VoiceTools */

#ifndef _Included_com_scy_myvoicechanger_VoiceTools
#define _Included_com_scy_myvoicechanger_VoiceTools
#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     com_scy_myvoicechanger_VoiceTools
 * Method:    changeVoice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scy_myvoicechanger_VoiceTools_changeVoice
  (JNIEnv *, jclass, jstring,jint);

#ifdef __cplusplus
}
#endif
#endif
